name: Terraform CI/CD (Hetzner)

on:
  push:
    paths:
      - 'iac/**.tf'
      - 'iac/clients/**'
      - 'iac/modules/**'
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client: [clienteA]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: |
          cd iac/clients/\${{ matrix.client }}
          terraform init -backend-config="key=\${{ matrix.client }}/terraform.tfstate"
        env:
          HCLOUD_TOKEN: \${{ secrets.HCLOUD_TOKEN_\${{ matrix.client | upper }} }}

      - name: Terraform Fmt
        run: cd iac && terraform fmt -check

      - name: Terraform Validate
        run: cd iac/clients/\${{ matrix.client }} && terraform validate

      - name: Terraform Plan
        run: |
          cd iac/clients/\${{ matrix.client }}
          terraform plan -var-file=terraform.tfvars -out=tfplan
        env:
          HCLOUD_TOKEN: \${{ secrets.HCLOUD_TOKEN_\${{ matrix.client | upper }} }}

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client: [clienteA]
    steps:
      - uses: actions/checkout@v3

      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: "\${{ matrix.client }}-tfplan"
          path: ./plans

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        run: |
          cd iac/clients/\${{ matrix.client }}
          terraform apply -auto-approve "tfplan"
        env:
          HCLOUD_TOKEN: \${{ secrets.HCLOUD_TOKEN_\${{ matrix.client | upper }} }}
