name: Terraform CI/CD (Hetzner)

on:
  push:
    paths:
      - 'iac/**.tf'
      - 'iac/clients/**'
      - 'iac/modules/**'
  workflow_dispatch:

jobs:
  plan:
    runs-on: self-hosted
    strategy:
      matrix:
        client: [clienteA]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        env:
          HCLOUD_TOKEN: ${{ secrets['HCLOUD_TOKEN_${{ matrix.client.toUpperCase() }}'] }}
          TF_VAR_hetzner_token: ${{ secrets['HCLOUD_TOKEN_${{ matrix.client.toUpperCase() }}'] }}
          TF_VAR_ssh_key_fingerprint: ${{ secrets['SSH_KEY_FINGERPRINT_${{ matrix.client.toUpperCase() }}'] }}
        run: |
          cd iac/clients/${{ matrix.client }}
          terraform init

      - name: Terraform Fmt
        run: cd iac && terraform fmt -check

      - name: Terraform Validate
        run: cd iac/clients/${{ matrix.client }} && terraform validate

      - name: Terraform Plan
        env:
          HCLOUD_TOKEN: ${{ secrets['HCLOUD_TOKEN_${{ matrix.client.toUpperCase() }}'] }}
          TF_VAR_hetzner_token: ${{ secrets['HCLOUD_TOKEN_${{ matrix.client.toUpperCase() }}'] }}
          TF_VAR_ssh_key_fingerprint: ${{ secrets['SSH_KEY_FINGERPRINT_${{ matrix.client.toUpperCase() }}'] }}
        run: |
          cd iac/clients/${{ matrix.client }}
          terraform plan -out=tfplan

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    strategy:
      matrix:
        client: [clienteA]
    steps:
      - uses: actions/checkout@v3

      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.client }}-tfplan
          path: ./plans

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        env:
          HCLOUD_TOKEN: ${{ secrets['HCLOUD_TOKEN_${{ matrix.client.toUpperCase() }}'] }}
          TF_VAR_hetzner_token: ${{ secrets['HCLOUD_TOKEN_${{ matrix.client.toUpperCase() }}'] }}
          TF_VAR_ssh_key_fingerprint: ${{ secrets['SSH_KEY_FINGERPRINT_${{ matrix.client.toUpperCase() }}'] }}
        run: |
          cd iac/clients/${{ matrix.client }}
          terraform apply -auto-approve "tfplan"
