name: Terraform CI/CD (Hetzner)

on:
  push:
    paths:
      - 'iac/**.tf'
      - 'iac/clients/**'
      - 'iac/modules/**'
  workflow_dispatch:

jobs:
  plan-clienteA:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN_CLIENTEA }}
          TF_VAR_hetzner_token: ${{ secrets.HCLOUD_TOKEN_CLIENTEA }}
          TF_VAR_ssh_key_fingerprint: ${{ secrets.SSH_KEY_FINGERPRINT_CLIENTEA }}
        run: |
          cd iac/clients/clienteA
          terraform init

      - name: Terraform Fmt
        run: cd iac && terraform fmt -check

      - name: Terraform Validate
        run: cd iac/clients/clienteA && terraform validate

      - name: Terraform Plan
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN_CLIENTEA }}
          TF_VAR_hetzner_token: ${{ secrets.HCLOUD_TOKEN_CLIENTEA }}
          TF_VAR_ssh_key_fingerprint: ${{ secrets.SSH_KEY_FINGERPRINT_CLIENTEA }}
        run: |
          cd iac/clients/clienteA
          terraform plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: clienteA-tfplan
          path: iac/clients/clienteA/tfplan

  apply-clienteA:
    needs: plan-clienteA
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: clienteA-tfplan
          path: ./plans

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN_CLIENTEA }}
          TF_VAR_hetzner_token: ${{ secrets.HCLOUD_TOKEN_CLIENTEA }}
          TF_VAR_ssh_key_fingerprint: ${{ secrets.SSH_KEY_FINGERPRINT_CLIENTEA }}
        run: |
          cd iac/clients/clienteA
          terraform apply -auto-approve "../plans/tfplan"
